### ISSUE TITLE
Font Transformer vs W3C Spec

### ISSUE THREAD

**Issue by jkinley** [lukasoppermann/style-dictionary-utils#34]
Hi Lukas!

I am wondering about the font transformer that you have and inconsistency with the spec. They use letter spacing you are using font style. Am I missing something?

Your transformer:

```
{
  typography: {
    body: {
      value: {
        fontWeight: 500,
        fontSize: "16px",
        lineHeight: "22px",
        fontFamily: "Helvetica",
        fontStyle: "italic"
      },
      $type: "typography"
    }
  }
}

```

W3C Spec

```

"heading-level-1": {
  "$type": "typography",
    "$value": {
      "fontFamily": "Roboto",
      "fontSize": "42px",
      "fontWeight": 700,
      "letterSpacing": "0.1px",
      "lineHeight": 1.2
}

```

**Comment by lukasoppermann** [comment]
Hey @jkinley this is correct. The reason is that the css font property does not support letterSpacing, but it does support fontStyle which again w3c does not support.

So it makes sense to allow fontStyle (you are free to omit this prop if you don't need it).

Since style dictionary can't split tokens, we can't support letterSpacing as we can only output one token `font`.

Hope that makes sense. Feel free to reopen if I missed something.
